print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print('widebody')
print('widestbodies')
print('United States of America')
print('I am enjoying 30 days of python')

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['widebody', 'python', 'finland']))
print(type('widebody'))
print(type('widestbodies'))
print(type('United Sates of America'))
